service: gsheet-service
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    GOOGLE_API_KEYS: 'xxx'
functions:
  gsheetApi:
    handler: handler.endpoint
    events:
      - http:
          path: sheets/{id}
          method: get
          cors: true